# Use official Node.js image
FROM node:14

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the app
COPY . .

# Build the app
RUN npm run build

# Use a lightweight web server to serve static files
RUN npm install -g serve

# Expose port
EXPOSE 5000

# Start the app
CMD ["serve", "-s", "build", "-l", "5000"]
